package generator

import (
	"fmt"

	. "github.com/dave/jennifer/jen"
	"github.com/gagliardetto/anchor-go/idl"
	"github.com/gagliardetto/anchor-go/tools"
)

func (g *Generator) genfile_events() (*OutputFile, error) {
	file := NewFile(g.options.Package)
	file.HeaderComment("Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.")
	file.HeaderComment("This file contains parsers for the events defined in the IDL.")

	// Generate event type structs with GetDiscriminator methods
	{
		for _, event := range g.idl.Events {
			eventCode, err := g.gen_eventType(event)
			if err != nil {
				return nil, fmt.Errorf("error generating event type for %s: %w", event.Name, err)
			}
			file.Add(eventCode)
		}
	}

	names := []string{}
	{
		for _, event := range g.idl.Events {
			names = append(names, tools.ToCamelUpper(event.Name))
		}
	}
	{
		code, err := g.gen_eventParser(names)
		if err != nil {
			return nil, fmt.Errorf("error generating event parser: %w", err)
		}
		file.Add(code)
	}

	return &OutputFile{
		Name: "events.go",
		File: file,
	}, nil
}

func (g *Generator) gen_eventParser(eventNames []string) (Code, error) {
	code := Empty()

	// Generate Event interface
	code.Line().Line()
	code.Comment("Event interface defines common methods for all event types")
	code.Line()
	code.Type().Id("Event").Interface(
		Id("Parsable"),
	)

	// AnchorEmitCPIDiscriminator is the 8-byte sentinel that Anchor's emit_cpi!
	// macro prepends to event data when an event is emitted as an inner CPI
	// instruction. Anchor stores the discriminator as a u64 (0x1d9acb512ea545e4)
	// and emits it on the wire as little-endian bytes; that's what we match
	// here. Consumers that read inner-instruction data off-chain need this to
	// strip the prefix before calling ParseEvent.
	code.Line().Line()
	code.Comment("AnchorEmitCPIDiscriminator is the 8-byte sentinel that Anchor's emit_cpi! macro")
	code.Comment("prepends to event data when emitting events as inner CPI instructions.")
	code.Comment("It mirrors anchor-lang's EVENT_IX_TAG_LE constant. See ParseEmitCPIEvent.")
	code.Line()
	code.Var().Id("AnchorEmitCPIDiscriminator").Op("=").Index(Lit(8)).Byte().Values(
		Lit(228), Lit(69), Lit(165), Lit(46), Lit(81), Lit(203), Lit(154), Lit(29),
	)

	// ParseAnyEvent is retained as a backward-compatible alias for ParseEvent
	// so existing internal callers (and any downstream consumers of the older
	// surface) keep compiling. We use godoc's "Deprecated:" marker, with the
	// recommended blank doc-comment line above it, so IDEs and `go doc`
	// surface the migration hint to ParseEvent.
	code.Line().Line()
	code.Comment("ParseAnyEvent parses event data into any known event type.")
	code.Comment("")
	code.Comment("Deprecated: use ParseEvent instead.")
	code.Line()
	code.Func().Id("ParseAnyEvent").
		Params(Id("eventData").Index().Byte()).
		Params(Any(), Error()).
		BlockFunc(func(block *Group) {
			// Preserve the historical (any, error) signature: assign to a typed
			// local first so the implicit Event->any conversion happens during
			// assignment rather than in a multi-value return tuple (which Go rejects).
			block.List(Id("event"), Id("err")).Op(":=").Id("ParseEvent").Call(Id("eventData"))
			block.Return(Id("event"), Id("err"))
		})

	// Generate ParseEvent function. The discriminator error inside this
	// function says "failed to read" rather than "failed to peek" because
	// ReadDiscriminator advances the decoder; the previous "peek" wording
	// would mislead anyone debugging from the error message.
	code.Line().Line()
	{
		code.Func().Id("ParseEvent").
			Params(Id("eventData").Index().Byte()).
			Params(Id("Event"), Error()).
			BlockFunc(func(block *Group) {
				block.Id("decoder").Op(":=").Qual(PkgBinary, "NewBorshDecoder").Call(Id("eventData"))
				block.List(Id("discriminator"), Err()).Op(":=").Id("decoder").Dot("ReadDiscriminator").Call()

				block.If(Err().Op("!=").Nil()).Block(
					Return(
						Nil(),
						Qual("fmt", "Errorf").Call(Lit("failed to read event discriminator: %w"), Err()),
					),
				)

				block.Switch(Id("discriminator")).BlockFunc(func(switchBlock *Group) {
					for _, name := range eventNames {
						switchBlock.Case(Id(FormatEventDiscriminatorName(name))).Block(
							Id("value").Op(":=").New(Id(name)),
							Err().Op(":=").Id("value").Dot("UnmarshalWithDecoder").Call(Id("decoder")),
							If(Err().Op("!=").Nil()).Block(
								Return(
									Nil(),
									Qual("fmt", "Errorf").Call(Lit("failed to unmarshal event as "+name+": %w"), Err()),
								),
							),
							Return(Id("value"), Nil()),
						)
					}
					switchBlock.Default().Block(
						Return(Nil(), Qual("fmt", "Errorf").Call(Lit("unknown discriminator: %s"), Qual(PkgBinary, "FormatDiscriminator").Call(Id("discriminator")))),
					)
				})
			})
	}
	// ParseEventTyped is the single dispatcher used by both the dynamic
	// ParseEvent (above) and the typed ParseEvent_<Name> wrappers (below).
	// Centralising the parse + type-assert logic here keeps the wrappers as
	// one-liners and avoids duplicating discriminator/decoder bookkeeping
	// per event.
	code.Line().Line()
	code.Comment("ParseEventTyped parses event data and returns a specific event type")
	code.Comment("T must implement the Event interface")
	code.Line()
	code.Func().Id("ParseEventTyped").
		Types(Id("T").Id("Event")).
		Params(Id("eventData").Index().Byte()).
		Params(Id("T"), Error()).
		BlockFunc(func(block *Group) {
			block.Id("event").Op(",").Id("err").Op(":=").Id("ParseEvent").Call(Id("eventData"))
			block.If(Id("err").Op("!=").Nil()).Block(
				Return(Op("*").New(Id("T")), Id("err")),
			)
			block.Id("typed").Op(",").Id("ok").Op(":=").Id("event").Assert(Id("T"))
			block.If(Op("!").Id("ok")).Block(
				Return(Op("*").New(Id("T")), Qual("fmt", "Errorf").Call(Lit("event is not of expected type"))),
			)
			block.Return(Id("typed"), Nil())
		})
	// ParseEmitCPIEvent strips Anchor's emit_cpi! sentinel from the front of
	// inner-instruction data before parsing as an event. Use this when reading
	// events from on-chain transaction inner-instruction logs, where the
	// payload is [AnchorEmitCPIDiscriminator || event_discriminator || borsh_payload].
	code.Line().Line()
	code.Comment("ParseEmitCPIEvent parses event data wrapped by Anchor's emit_cpi! macro.")
	code.Comment("CPI-emitted event data is prefixed with AnchorEmitCPIDiscriminator; this")
	code.Comment("strips the prefix and delegates to ParseEvent.")
	code.Line()
	code.Func().Id("ParseEmitCPIEvent").
		Params(Id("data").Index().Byte()).
		Params(Id("Event"), Error()).
		BlockFunc(func(block *Group) {
			block.If(Len(Id("data")).Op("<").Lit(8)).Block(
				Return(Nil(), Qual("fmt", "Errorf").Call(Lit("emit_cpi event data too short: expected at least 8 bytes, got %d"), Len(Id("data")))),
			)
			block.If(Op("!").Qual("bytes", "Equal").Call(
				Id("data").Index(Empty(), Lit(8)),
				Id("AnchorEmitCPIDiscriminator").Index(Op(":")),
			)).Block(
				Return(Nil(), Qual("fmt", "Errorf").Call(Lit("data is not an anchor emit_cpi event (missing discriminator)"))),
			)
			block.Return(Id("ParseEvent").Call(Id("data").Index(Lit(8), Empty())))
		})

	// Per-event typed wrappers. We keep the historical ParseEvent_<Name>
	// entry points so callers don't have to use generics; the actual parsing
	// happens once inside ParseEventTyped above.
	{
		code.Line().Line()
		for _, name := range eventNames {
			code.Func().Id("ParseEvent_"+name).
				Params(Id("eventData").Index().Byte()).
				Params(Op("*").Id(name), Error()).
				Block(
					Return(Id("ParseEventTyped").Types(Op("*").Id(name)).Call(Id("eventData"))),
				)
			code.Line().Line()
		}
	}
	return code, nil
}

func (g *Generator) gen_eventType(event idl.IdlEvent) (Code, error) {
	code := Empty()
	eventName := tools.ToCamelUpper(event.Name)

	// Find the event type definition in the types array
	var eventTypeDef *idl.IdlTypeDef
	for i := range g.idl.Types {
		if g.idl.Types[i].Name == event.Name {
			eventTypeDef = &g.idl.Types[i]
			break
		}
	}

	// If no type definition found, generate a simple event struct with just the discriminator method
	if eventTypeDef == nil {
		// Generate empty event struct
		code.Line().Line()
		code.Comment(fmt.Sprintf("%s is an event", eventName))
		code.Line()
		code.Type().Id(eventName).Struct()
	} else {
		// Event type struct is already generated in types.go
		// We just need to add the methods
		code.Line().Line()
	}

	// Generate GetDiscriminator method
	code.Func().Params(Id("obj").Op("*").Id(eventName)).Id("GetDiscriminator").
		Params().
		Params(Index().Byte()).
		Block(
			Return(Id(FormatEventDiscriminatorName(eventName)).Index(Op(":"))),
		)

	// GetName emits the IDL-defined event name. Pairs with GetDiscriminator
	// and satisfies the shared Parsable interface (see instructions.go).
	// Letting callers identify a parsed Event by name avoids forcing them to
	// type-switch over every concrete event type.
	code.Line().Line()
	code.Func().Params(Id("obj").Op("*").Id(eventName)).Id("GetName").
		Params().
		String().
		Block(
			Return(Lit(event.Name)),
		)

	if eventTypeDef != nil {
		if eventStruct, ok := eventTypeDef.Ty.(*idl.IdlTypeDefTyStruct); ok {
			getterSpecs := getterSpecsFromDefinedFields(eventStruct.Fields)
			if len(getterSpecs) > 0 {
				code.Add(genGetterMethods(eventName, getterSpecs))
			}
		}
	}

	// Generate UnmarshalWithDecoder method if type definition doesn't exist
	// (if it exists, it's already generated in types.go)
	if eventTypeDef == nil {
		code.Line().Line()
		code.Func().Params(Id("obj").Op("*").Id(eventName)).Id("UnmarshalWithDecoder").
			Params(Id("decoder").Op("*").Qual(PkgBinary, "Decoder")).
			Params(Error()).
			BlockFunc(func(block *Group) {
				block.Comment("Read and validate discriminator")
				block.List(Id("discriminator"), Err()).Op(":=").Id("decoder").Dot("ReadDiscriminator").Call()
				block.If(Err().Op("!=").Nil()).Block(
					Return(Qual("fmt", "Errorf").Call(Lit("failed to read event discriminator for %s: %w"), Lit(eventName), Err())),
				)
				block.If(Id("discriminator").Op("!=").Id(FormatEventDiscriminatorName(eventName))).Block(
					Return(
						Qual("fmt", "Errorf").Call(
							Lit("event discriminator mismatch for %s: expected %s, got %s"),
							Lit(eventName),
							Qual(PkgBinary, "FormatDiscriminator").Call(Id(FormatEventDiscriminatorName(eventName))),
							Qual(PkgBinary, "FormatDiscriminator").Call(Id("discriminator")),
						),
					),
				)
				block.Comment("No fields to unmarshal")
				block.Return(Nil())
			})
	}

	return code, nil
}
