package generator

import (
	"fmt"

	. "github.com/dave/jennifer/jen"
	"github.com/gagliardetto/anchor-go/idl"
	"github.com/gagliardetto/anchor-go/tools"
)

func (g *Generator) genfile_events() (*OutputFile, error) {
	file := NewFile(g.options.Package)
	file.HeaderComment("Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.")
	file.HeaderComment("This file contains parsers for the events defined in the IDL.")

	// Generate event type structs with GetDiscriminator methods
	{
		for _, event := range g.idl.Events {
			eventCode, err := g.gen_eventType(event)
			if err != nil {
				return nil, fmt.Errorf("error generating event type for %s: %w", event.Name, err)
			}
			file.Add(eventCode)
		}
	}

	names := []string{}
	{
		for _, event := range g.idl.Events {
			names = append(names, tools.ToCamelUpper(event.Name))
		}
	}
	{
		code, err := g.gen_eventParser(names)
		if err != nil {
			return nil, fmt.Errorf("error generating event parser: %w", err)
		}
		file.Add(code)
	}

	return &OutputFile{
		Name: "events.go",
		File: file,
	}, nil
}

func (g *Generator) gen_eventParser(eventNames []string) (Code, error) {
	code := Empty()

	// Generate Event interface
	code.Line().Line()
	code.Comment("Event interface defines common methods for all event types")
	code.Line()
	code.Type().Id("Event").Interface(
		Id("Parsable"),
	)

	// Generate ParseEvent function
	code.Line().Line()
	{
		code.Func().Id("ParseEvent").
			Params(Id("eventData").Index().Byte()).
			Params(Id("Event"), Error()).
			BlockFunc(func(block *Group) {
				block.Id("decoder").Op(":=").Qual(PkgBinary, "NewBorshDecoder").Call(Id("eventData"))
				block.List(Id("discriminator"), Err()).Op(":=").Id("decoder").Dot("ReadDiscriminator").Call()

				block.If(Err().Op("!=").Nil()).Block(
					Return(
						Nil(),
						Qual("fmt", "Errorf").Call(Lit("failed to peek event discriminator: %w"), Err()),
					),
				)

				block.Switch(Id("discriminator")).BlockFunc(func(switchBlock *Group) {
					for _, name := range eventNames {
						switchBlock.Case(Id(FormatEventDiscriminatorName(name))).Block(
							Id("value").Op(":=").New(Id(name)),
							Err().Op(":=").Id("value").Dot("UnmarshalWithDecoder").Call(Id("decoder")),
							If(Err().Op("!=").Nil()).Block(
								Return(
									Nil(),
									Qual("fmt", "Errorf").Call(Lit("failed to unmarshal event as "+name+": %w"), Err()),
								),
							),
							Return(Id("value"), Nil()),
						)
					}
					switchBlock.Default().Block(
						Return(Nil(), Qual("fmt", "Errorf").Call(Lit("unknown discriminator: %s"), Qual(PkgBinary, "FormatDiscriminator").Call(Id("discriminator")))),
					)
				})
			})
	}
	{
		code.Line().Line()
		// for each event, generate a function to parse it:
		for _, name := range eventNames {
			discriminatorName := FormatEventDiscriminatorName(name)

			code.Func().Id("ParseEvent_"+name).
				Params(Id("eventData").Index().Byte()).
				Params(Op("*").Id(name), Error()).
				BlockFunc(func(block *Group) {
					block.Id("decoder").Op(":=").Qual(PkgBinary, "NewBorshDecoder").Call(Id("eventData"))
					block.List(Id("discriminator"), Err()).Op(":=").Id("decoder").Dot("ReadDiscriminator").Call()

					block.If(Err().Op("!=").Nil()).Block(
						Return(
							Nil(),
							Qual("fmt", "Errorf").Call(Lit("failed to peek discriminator: %w"), Err()),
						),
					)

					block.If(Id("discriminator").Op("!=").Id(discriminatorName)).Block(
						Return(Nil(), Qual("fmt", "Errorf").Call(Lit("expected discriminator %v, got %s"), Id(discriminatorName), Qual(PkgBinary, "FormatDiscriminator").Call(Id("discriminator")))),
					)

					block.Id("event").Op(":=").New(Id(name))
					block.Err().Op("=").Id("event").Dot("UnmarshalWithDecoder").Call(Id("decoder"))

					block.If(Err().Op("!=").Nil()).Block(
						Return(
							Nil(),
							Qual("fmt", "Errorf").Call(Lit("failed to unmarshal event of type "+name+": %w"), Err()),
						),
					)

					block.Return(Id("event"), Nil())
				})
			code.Line().Line()
		}
	}
	return code, nil
}

func (g *Generator) gen_eventType(event idl.IdlEvent) (Code, error) {
	code := Empty()
	eventName := tools.ToCamelUpper(event.Name)

	// Find the event type definition in the types array
	var eventTypeDef *idl.IdlTypeDef
	for i := range g.idl.Types {
		if g.idl.Types[i].Name == event.Name {
			eventTypeDef = &g.idl.Types[i]
			break
		}
	}

	// If no type definition found, generate a simple event struct with just the discriminator method
	if eventTypeDef == nil {
		// Generate empty event struct
		code.Line().Line()
		code.Comment(fmt.Sprintf("%s is an event", eventName))
		code.Line()
		code.Type().Id(eventName).Struct()
	} else {
		// Event type struct is already generated in types.go
		// We just need to add the methods
		code.Line().Line()
	}

	// Generate GetDiscriminator method
	code.Func().Params(Id("obj").Op("*").Id(eventName)).Id("GetDiscriminator").
		Params().
		Params(Index().Byte()).
		Block(
			Return(Id(FormatEventDiscriminatorName(eventName)).Index(Op(":"))),
		)

	// Generate UnmarshalWithDecoder method if type definition doesn't exist
	// (if it exists, it's already generated in types.go)
	if eventTypeDef == nil {
		code.Line().Line()
		code.Func().Params(Id("obj").Op("*").Id(eventName)).Id("UnmarshalWithDecoder").
			Params(Id("decoder").Op("*").Qual(PkgBinary, "Decoder")).
			Params(Error()).
			BlockFunc(func(block *Group) {
				block.Comment("Read and validate discriminator")
				block.List(Id("discriminator"), Err()).Op(":=").Id("decoder").Dot("ReadDiscriminator").Call()
				block.If(Err().Op("!=").Nil()).Block(
					Return(Qual("fmt", "Errorf").Call(Lit("failed to read event discriminator for %s: %w"), Lit(eventName), Err())),
				)
				block.If(Id("discriminator").Op("!=").Id(FormatEventDiscriminatorName(eventName))).Block(
					Return(
						Qual("fmt", "Errorf").Call(
							Lit("event discriminator mismatch for %s: expected %s, got %s"),
							Lit(eventName),
							Qual(PkgBinary, "FormatDiscriminator").Call(Id(FormatEventDiscriminatorName(eventName))),
							Qual(PkgBinary, "FormatDiscriminator").Call(Id("discriminator")),
						),
					),
				)
				block.Comment("No fields to unmarshal")
				block.Return(Nil())
			})
	}

	return code, nil
}
